# Generated by Django 5.0.3 on 2025-03-05 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ngày bạn báo cáo sự kiện này.', verbose_name='Ngày báo cáo'),
        ),
    ]
